---
title: "Mid-Term Exam #1"
subtitle: "Due date: 6 October (11:59 pm)"
format: 
  html: 
    self-contained: true
    toc: true
editor: visual
execute: 
  message: false
  warning: false
---

Please read all of the questions and tables carefully and follow all instructions. Each question has an allotted point value. Be as thorough and specific as possible; extra calculations and incorrect information, even in the presence of correct information, will result in point deductions. Be sure to show all formulas and all necessary work to answer the questions. Upload your completed exam to the ELMs course site (attach to Exam #1) and to your Github repositories.

::: callout-note
While this is an open-note exam, you are not to receive assistance from anyone else. As usual, the Honor Code applies.
:::

## Conceptual Questions

**Total points: 10**

Please include all work (and computations) necessary to answer the questions.

### Question 1

*1 point*

The following is a list of observed values, ordered from lowest to highest: 62, 63, 63, 64, 66, 67, 68, 68, 69, 70, 71, 72, 72, 74, 75, 76. What is an accurate five-number summary for these data?

### Question 2

*1 point*

Suppose that the median, Q1, and Q3 from question #1 is an accurate representation of a second (hypothetical) distribution. Based on what this information tells you about this second distribution, which of the following numbers would be a suspected outlier?

A.  76
B.  62
C.  83
D.  Both (A) and (C)
E.  All of the above
F.  None of the above, or cannot be determined from the information given.

### Question 3

*1 point*

The median age of ten people in a room is 50 years. One 40-year-old person leaves the room. What can we expect will happen to the median age for the remaining nine people? Do we know the median age of those nine people; if so, what is it?

### Question 4

*1 point*

The mean age of ten people in a room is 50 years. One 70-years-old person leaves the room. What can we expect will happen to the mean age for the remaining nine people? Do we know the mean age of those nine people; if so, what is it?

### Question 5

*1 point*

The mean age of ten people in a room is 50 years and the standard deviation is 3 years. One person leaves the room, and both the mean and the standard deviation become larger. What do we know about the age of that person?

### Question 6

*1 point*

The distribution of some variable has a median that is smaller than its mean. Which of the following statements about the distribution's shape is most consistent with this information?

A.  The shape of the distribution would be symmetric
B.  The shape of the distribution would be skewed left
C.  The shape of the distribution would be skewed right
D.  None of the above -- cannot be determined from the information given.

### Question 7

*1 point*

Suppose I want to test the hypothesis that the U.S. public's approval of the president is higher when people have more positive perceptions of the U.S. economy. To test this hypothesis, I conduct a survey of individual-level attitudes. Which of the following research design strategies should I expect to exhibit both the greatest sampling variability (in the context of repeated sampling) and the lowest degree of expected sampling bias?

A.  A random sample of 1,200 people from a list of all U.S. residential addresses
B.  A random sample of 600 people from a list of all registered students at the University of Maryland
C.  A random sample of 1,200 people from a list of all registered students at the University of Maryland
D.  A random sample of 600 people from a list of all U.S. residential addresses.

### Question 8

*1 point*

Which of those research design strategies should I expect to exhibit the lowest degree of expected sampling bias?

### Question 9

*1 point*

I hypothesize that, as people become more conservative, they watch NASCAR more often. My measure of conservatism is a three category variable—not conservative, somewhat conservative, very conservative. My measure of NASCAR viewing is four category—none, occasionally, often, frequently. I construct a cross tab to examine this hypothesis. What distributions would I compare to test my hypothesis?

### Question 10

*1 point*

I examine the correlation between my independent variable and my dependent variable, and find a correlation coefficient of 0.9. What does this tell me about the causal effect of the IV on the DV?

## Applied Questions

Please include your R code. All data sets referenced below are available through the `polisciols` R package.

**Total points: 20**

### Question 1

*5 points total*

I am interested in exploring US voters' views of Donald Trump prior to the last US Presidential election. Use the `nes` data set in the `polisciols` R package to answer the following questions.

#### Part A

Plot the distribution of NES respondents' answers to the following question: On a scale from 0 to 100, how would you rate Donald Trump? Describe that distribution. Include the five-number summary in your answer.

::: callout-note
These responses are stored in the `therm_trump` variable.
:::

#### Part B

If I were to select a respondent at random, what is the answer they most likely provided to this question?

#### Part C

I hypothesize that people who hold different views about the size of the difference in incomes between rich people and poor people in the United States today compared to 20 years ago also have different views about Donald Trump. Group respondents based on their views about this difference and then plot, within each group, the respondents' answers to the question about their views of Donald Trump.

::: callout-note
Respondents' answer to the question - Do you think the difference in incomes between rich people and poor people in the United States today is larger, smaller, or about the same as it was 20 years ago? - are stored in the `income_gap` variable.
:::

#### Part D

Do these responses support my hypothesis?

#### Part E

If I were to select an individual who thought the difference in incomes between rich people and poor people in the United States today is **smaller** than it was 20 years ago, what is the most likely answer they provided to the question about their views of Donald Trump?

### Question 2

*5 points*

I hypothesize that providing free child care at election voting stations will increase turnout among families with young children. Design an experiment to test this hypothesis. Describe any shortcomings your experimental design may have.

### Question 3

*5 points*

I hypothesize that countries that share similar regime types are more likely to sign mutual defense agreements with each other than countries that do not share similar regimes. Use the `alliances_regime` data set from the `polisciols` R package to answer the following questions.

#### Part A

Construct a cross tab of these variables.

#### Part B

Interpret your cross tab. Do these data support my hypothesis?

### Question 4

*5 points*

I am interested in exploring the relationship between each country's wealth and its renewable energy use. To do this, I collect data on each country's GDP per capita (as a proxy for wealth) and the proportion of its overall energy consumption that is produced using renewable energy sources. Use the `renewables.csv` dataset published on ELMs to answer the following questions.

#### Part A

What proportion of overall energy consumption do the middle 50 percent of countries produce using renewable energy sources? Include an appropriate plot in your answer.

#### Part B

Describe the distribution of GDP per capita across countries globally. Include an appropriate plot in your answer.

#### Part C

Is the relationship between renewable energy use and wealth linear? What about the relationship between renewable energy use and each country's logged GDP per capita? Include two plots (one of each relationship) in your answer.

#### Part D

Describe the direction and strength of the relationship between renewable energy use and wealth.
